### PR TITLE
Gv 126 remove force update from unittest

### LINKED ISSUE #126: Remove force_update from property unit test
force_update should be replaced by calling

```
property.update()
property.has_updated_since_last_resolve = False
```

### PR DESCRIPTION
**Pull request by giovannivolpe**

### CODE REVIEW

**Comment by giovannivolpe** [comment]
@BenjaminMidtvedt 
With PropertyDict the new approach does not seem to work. with the new approach.

For example, see properties_example 3.

It updates correctly with:
property_dict.update(force_update=True)

But it doesn't updated with:
property_dict.update()
or
property_dict.has_updated_since_last_resolve = False
property_dict.update()

**Comment by BenjaminMidtvedt** [comment]
@giovannivolpe Ah, you're right. `has_updated_since_last_resolve` is an attribute of Property, not PropertyDict. There is a way around this, by calling `current_property_dict(is_resolving=True)`. This should make the PropertyDict correctly set `has_updated_since_last_resolve` of all properties.

**Comment by giovannivolpe** [comment]
@BenjaminMidtvedt ok, the we can just call it with `property_dict.update(force_update=True)` and explain this in the example?

**Review by giovannivolpe — COMMENTED** [review]
nothing, I wrote a comment in wrong place

**Comment by BenjaminMidtvedt** [comment]
I have made the necessary change, the notebook should be working as expected without force_update=True now.

**Review by BenjaminMidtvedt — APPROVED** [review]

**Pull request merged**
